[package]
name = "obj"
version = "0.1.0"
edition = "2021"

[dependencies]
app = { path = "../apps/helloworld", package = "helloworld" }
platform = { path = "../platforms/qemu-sifive_u", package = "qemu-sifive_u" }
stdio = { path = "../libs/stdio" }

[build-dependencies]
linker = { path = "../platforms/qemu-sifive_u-ld", package = "qemu-sifive_u-ld" }
